package com.dtrosien.rowdata4s.datatype

import com.dtrosien.rowdata4s.*
import com.dtrosien.rowdata4s.annotations.{Annotations, Names}
import magnolia1.{AutoDerivation, CaseClass, SealedTrait}
import org.apache.flink.table.api.DataTypes
import org.apache.flink.table.types.DataType

import java.nio.ByteBuffer
import java.sql.Timestamp
import java.time.*
import java.util.{Date, UUID}

/** A [[DataTypeFor]] generates an Avro Schema for a Scala or Java type.
  *
  * For example, a DataTypeFor[String] could return a datatype of type DataType.STRING, and a DataTypeFor[Int] could
  * return a datatype of type DataType.INT
  */
trait DataTypeFor[T] {
  self =>

  /** Returns the flink [[DataType]] generated by this typeclass
    */
  def dataType: DataType

  /** Changes the type of this DataTypeFor to the desired type `U` without any other modifications.
    *
    * @tparam U
    *   new type for DataTypeFor.
    */
  final def forType[U]: DataTypeFor[U] = map[U](identity)

  /** Creates a DataTypeFor[U] by applying a function DataType => DataType to the datatype generated by this instance.
    */
  final def map[U](fn: DataType => DataType): DataTypeFor[U] = {
    new DataTypeFor[U] {
      override def dataType: DataType = fn(self.dataType)
    }
  }
}

object DataTypeFor
    extends PrimitiveSchemas
    with BigDecimalSchemas
    with MagnoliaDerivedDataTypes
    with ByteIterableSchemas
    with CollectionSchemas
    with OptionSchemas
    with StringSchemas
    with TemporalSchemas
    with TupleSchemas {

  /** Returns a [[SchemaFor]] that returns the given schema.
    */
  def apply[T](t: DataType): DataTypeFor[T] = new DataTypeFor[T] {
    override def dataType: DataType = t
  }

  def from[T](f: => DataType): DataTypeFor[T] = new DataTypeFor[T] {
    override def dataType: DataType = f
  }

  def apply[T](using dataTypeFor: DataTypeFor[T]): DataTypeFor[T] = dataTypeFor
}

// ==============================================
// Magnolia   ===================================
// ==============================================

trait MagnoliaDerivedDataTypes extends AutoDerivation[DataTypeFor]:

  def join[T](ctx: CaseClass[DataTypeFor, T]): DataTypeFor[T] =
    DatatypeShape.of(ctx) match {
      case CaseClassShape.Record    => Records.dataType(ctx)
      case CaseClassShape.ValueType => ???
    }

  override def split[T](ctx: SealedTrait[DataTypeFor, T]): DataTypeFor[T] =
    DatatypeShape.of[T](ctx) match {
      case SealedTraitShape.Enum      => SealedTraits.dataType(ctx)
      case SealedTraitShape.TypeUnion => ???
    }

enum CaseClassShape:
  case ValueType, Record

enum SealedTraitShape:
  case TypeUnion, Enum

object DatatypeShape:

  def of[T](ctx: SealedTrait[?, T]): SealedTraitShape = {
    val allSubtypesAreObjects = ctx.subtypes.forall(_.isObject)
    if ctx.isEnum || allSubtypesAreObjects then SealedTraitShape.Enum else SealedTraitShape.TypeUnion
  }

  def of[Typeclass[_], T](ctx: CaseClass[Typeclass, T]): CaseClassShape =
    if ctx.isValueClass then CaseClassShape.ValueType else CaseClassShape.Record

// ==============================================
// Sealed Trait and Enum (to ROW and Field)   ===
// ==============================================

object SealedTraits {
  def dataType[T](ctx: SealedTrait[DataTypeFor, T]): DataTypeFor[T] = {

    val names = Names(ctx.typeInfo, Annotations(ctx.annotations))

    // It currently appears (magnolia1, v 1) that all the enum elements carry the same annotation set
    // as the enumeration symbol itself, which leads to name clash in the generated schema.
    // Annotations that are attached to the enum elements are not visible here.
//    val symbols = ctx.subtypes.sortBy(_.index).map { st =>
//      Names(
//        st.typeInfo,
//        Annotations(
//          st.annotations.filter {
//            case tn: TableName => tn.name != names.name
//            case _ => true
//          }
//        )
//      )
//    }
    new DataTypeFor[T] {
      override def dataType: DataType = DataTypes.ROW(DataTypes.STRING()) // todo add symbol datatypes
    }
  }
}

// ==============================================
// Row and Field   ==============================
// ==============================================

object Records:

  def dataType[T](ctx: CaseClass[DataTypeFor, T]): DataTypeFor[T] = {

    val annos  = Annotations(ctx)
    val naming = Names(ctx.typeInfo, annos)

    val fields = ctx.params.toList.flatMap { param =>
      val fieldAnnos = Annotations(param.annotations)
      if fieldAnnos.transient then None
      else {
        val name = fieldAnnos.name.getOrElse(param.label)
        Some(DataTypes.FIELD(name, param.typeclass.dataType))
      }
    }

    val record = DataTypes.ROW(fields*).notNull()

    new DataTypeFor[T] {
      override def dataType: DataType = record
    }
  }

// ==============================================
// Primitives   =================================
// ==============================================

trait PrimitiveSchemas:
  given intDataTypeFor: DataTypeFor[Int] = DataTypeFor[Int](DataTypes.INT.notNull)
  given DataTypeFor[Byte]                = intDataTypeFor.forType
  given DataTypeFor[Short]               = intDataTypeFor.forType
  given DataTypeFor[Long]                = DataTypeFor[Long](DataTypes.BIGINT.notNull)
  given DataTypeFor[Float]               = DataTypeFor[Float](DataTypes.FLOAT.notNull)
  given DataTypeFor[Double]              = DataTypeFor[Double](DataTypes.DOUBLE.notNull)
  given DataTypeFor[scala.Boolean]       = DataTypeFor[Boolean](DataTypes.BOOLEAN.notNull)
  given DataTypeFor[ByteBuffer]          = DataTypeFor[ByteBuffer](DataTypes.BYTES.notNull)

// ==============================================
// Big Decimal   ================================
// ==============================================

case class ScalePrecision(scale: Int, precision: Int)

object ScalePrecision {
  given default: ScalePrecision = ScalePrecision(2, 8)
}

trait BigDecimalSchemas:
  given (using sp: ScalePrecision): DataTypeFor[BigDecimal] = BigDecimalSchemaFor(sp)

class BigDecimalSchemaFor(sp: ScalePrecision) extends DataTypeFor[BigDecimal]:
  override def dataType: DataType = DataTypes.DECIMAL(sp.precision, sp.scale).notNull

// ==============================================
// Bytes   ======================================
// ==============================================

trait ByteIterableSchemas:
  given ByteArraySchemaFor: DataTypeFor[Array[Byte]]   = DataTypeFor[Array[Byte]](DataTypes.BYTES.notNull)
  given ByteListSchemaFor: DataTypeFor[List[Byte]]     = ByteArraySchemaFor.forType
  given ByteSeqSchemaFor: DataTypeFor[Seq[Byte]]       = ByteArraySchemaFor.forType
  given ByteVectorSchemaFor: DataTypeFor[Vector[Byte]] = ByteArraySchemaFor.forType

// ==============================================
// Collections   ================================
// ==============================================

trait CollectionSchemas:

  private def buildIterableSchemaFor[C[X] <: Iterable[X], T](using dataTypeFor: DataTypeFor[T]): DataTypeFor[C[T]] =
    dataTypeFor.map(DataTypes.ARRAY(_).notNull)

  given [T](using dataTypeFor: DataTypeFor[T]): DataTypeFor[Array[T]] = new DataTypeFor[Array[T]]:
    override def dataType: DataType = DataTypes.ARRAY(dataTypeFor.dataType).notNull

  given [T](using dataTypeFor: DataTypeFor[T]): DataTypeFor[Seq[T]] = buildIterableSchemaFor[Seq, T]

  given [T](using DataTypeFor[T]): DataTypeFor[Set[T]] = buildIterableSchemaFor[Set, T]

  given [T](using DataTypeFor[T]): DataTypeFor[Vector[T]] = buildIterableSchemaFor[Vector, T]

  given [T](using dataTypeFor: DataTypeFor[T]): DataTypeFor[List[T]] = buildIterableSchemaFor[List, T]

  given [V](using dataTypeFor: DataTypeFor[V]): DataTypeFor[Map[String, V]] =
    dataTypeFor.map(DataTypes.MAP(DataTypes.STRING.notNull, _).notNull)

// ==============================================
// Option   =====================================
// ==============================================

trait OptionSchemas {

  given DataTypeFor[None.type] = NoneDataTypeFor

  given [T](using dataTypeFor: DataTypeFor[T]): DataTypeFor[Option[T]] = new DataTypeFor[Option[T]] {
    override def dataType: DataType = dataTypeFor.dataType.nullable()
  }
}

object NoneDataTypeFor extends DataTypeFor[None.type]:
  private val s                   = DataTypes.NULL()
  override def dataType: DataType = s

// ==============================================
// String   =====================================
// ==============================================

trait StringSchemas:
  given StringSchemaFor: DataTypeFor[String] = DataTypeFor[String](DataTypes.STRING.notNull)
  given DataTypeFor[CharSequence]            = StringSchemaFor.forType
  given DataTypeFor[UUID]                    = StringSchemaFor.forType

// ==============================================
// Temporal   ===================================
// ==============================================

trait TemporalSchemas:
  given InstantSchemaFor: DataTypeFor[Instant] =
    DataTypeFor(DataTypes.TIMESTAMP(3).notNull)
  // java.util.Date behaves like an instant
  given UtilDateSchemaFor: DataTypeFor[java.util.Date] =
    DataTypeFor(DataTypes.TIMESTAMP_WITH_LOCAL_TIME_ZONE(3).notNull)
  given SqlDateSchemaFor: DataTypeFor[java.sql.Date] =
    DataTypeFor(DataTypes.DATE.notNull)
  given LocalDateSchemaFor: DataTypeFor[LocalDate] =
    DataTypeFor(DataTypes.DATE.notNull)
  given LocalDateTimeSchemaFor: DataTypeFor[LocalDateTime] =
    DataTypeFor(DataTypes.BIGINT.notNull)
  given OffsetDateTimeSchemaFor: DataTypeFor[OffsetDateTime] =
    DataTypeFor(DataTypes.STRING.notNull)
  given LocalTimeSchemaFor: DataTypeFor[LocalTime] =
    DataTypeFor(DataTypes.TIME(6).notNull)
  given TimestampSchemaFor: DataTypeFor[Timestamp] =
    DataTypeFor(DataTypes.TIMESTAMP(3).notNull)

// ==============================================
// Tuples   =====================================
// ==============================================

trait TupleSchemas:

  given [A, B](using a: DataTypeFor[A], b: DataTypeFor[B]): DataTypeFor[Tuple2[A, B]] = DataTypeFor.from {
    val fields = java.util.ArrayList[DataTypes.Field]()
    fields.add(DataTypes.FIELD("_1", a.dataType))
    fields.add(DataTypes.FIELD("_2", b.dataType))
    DataTypes.ROW(fields).notNull
  }

  given [A, B, C](using a: DataTypeFor[A], b: DataTypeFor[B], c: DataTypeFor[C]): DataTypeFor[Tuple3[A, B, C]] =
    DataTypeFor.from {
      val fields = java.util.ArrayList[DataTypes.Field]()
      fields.add(DataTypes.FIELD("_1", a.dataType))
      fields.add(DataTypes.FIELD("_2", b.dataType))
      fields.add(DataTypes.FIELD("_3", c.dataType))
      DataTypes.ROW(fields).notNull
    }

  given [A, B, C, D](using
      a: DataTypeFor[A],
      b: DataTypeFor[B],
      c: DataTypeFor[C],
      d: DataTypeFor[D]
  ): DataTypeFor[Tuple4[A, B, C, D]] = DataTypeFor.from {
    val fields = java.util.ArrayList[DataTypes.Field]()
    fields.add(DataTypes.FIELD("_1", a.dataType))
    fields.add(DataTypes.FIELD("_2", b.dataType))
    fields.add(DataTypes.FIELD("_3", c.dataType))
    fields.add(DataTypes.FIELD("_4", d.dataType))
    DataTypes.ROW(fields).notNull
  }

  given [A, B, C, D, E](using
      a: DataTypeFor[A],
      b: DataTypeFor[B],
      c: DataTypeFor[C],
      d: DataTypeFor[D],
      e: DataTypeFor[E]
  ): DataTypeFor[Tuple5[A, B, C, D, E]] = DataTypeFor.from {
    val fields = java.util.ArrayList[DataTypes.Field]()
    fields.add(DataTypes.FIELD("_1", a.dataType))
    fields.add(DataTypes.FIELD("_2", b.dataType))
    fields.add(DataTypes.FIELD("_3", c.dataType))
    fields.add(DataTypes.FIELD("_4", d.dataType))
    fields.add(DataTypes.FIELD("_5", e.dataType))
    DataTypes.ROW(fields).notNull
  }

  given [A, B, C, D, E, F](using
      a: DataTypeFor[A],
      b: DataTypeFor[B],
      c: DataTypeFor[C],
      d: DataTypeFor[D],
      e: DataTypeFor[E],
      f: DataTypeFor[F]
  ): DataTypeFor[Tuple6[A, B, C, D, E, F]] = DataTypeFor.from {
    val fields = java.util.ArrayList[DataTypes.Field]()
    fields.add(DataTypes.FIELD("_1", a.dataType))
    fields.add(DataTypes.FIELD("_2", b.dataType))
    fields.add(DataTypes.FIELD("_3", c.dataType))
    fields.add(DataTypes.FIELD("_4", d.dataType))
    fields.add(DataTypes.FIELD("_5", e.dataType))
    fields.add(DataTypes.FIELD("_6", e.dataType))
    DataTypes.ROW(fields).notNull
  }
